//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarsEngage
{
    using System;
    using System.Collections.Generic;
    
    public partial class cars_engage_2022
    {
        public short sno { get; set; }
        public string Make { get; set; }
        public string Model { get; set; }
        public string Variant { get; set; }
        public string Ex_Showroom_Price { get; set; }
        public string Displacement { get; set; }
        public string Cylinders { get; set; }
        public string Valves_Per_Cylinder { get; set; }
        public string Drivetrain { get; set; }
        public string Cylinder_Configuration { get; set; }
        public string Emission_Norm { get; set; }
        public string Engine_Location { get; set; }
        public string Fuel_System { get; set; }
        public string Fuel_Tank_Capacity { get; set; }
        public string Fuel_Type { get; set; }
        public string Height { get; set; }
        public string Length { get; set; }
        public string Width { get; set; }
        public string Body_Type { get; set; }
        public string Doors { get; set; }
        public string City_Mileage { get; set; }
        public string Highway_Mileage { get; set; }
        public string ARAI_Certified_Mileage { get; set; }
        public string ARAI_Certified_Mileage_for_CNG { get; set; }
        public string Kerb_Weight { get; set; }
        public string Gears { get; set; }
        public string Ground_Clearance { get; set; }
        public string Front_Brakes { get; set; }
        public string Rear_Brakes { get; set; }
        public string Front_Suspension { get; set; }
        public string Rear_Suspension { get; set; }
        public string Front_Track { get; set; }
        public string Rear_Track { get; set; }
        public string Front_Tyre_Rim { get; set; }
        public string Rear_Tyre_Rim { get; set; }
        public string Power_Steering { get; set; }
        public string Power_Windows { get; set; }
        public string Power_Seats { get; set; }
        public string Keyless_Entry { get; set; }
        public string Power { get; set; }
        public string Torque { get; set; }
        public string Odometer { get; set; }
        public string Speedometer { get; set; }
        public string Tachometer { get; set; }
        public string Tripmeter { get; set; }
        public string Seating_Capacity { get; set; }
        public string Seats_Material { get; set; }
        public string Type { get; set; }
        public string Wheelbase { get; set; }
        public string Wheels_Size { get; set; }
        public string Start_Stop_Button { get; set; }
        public string C_12v_Power_Outlet { get; set; }
        public string Audiosystem { get; set; }
        public string Aux_in_Compatibility { get; set; }
        public string Average_Fuel_Consumption { get; set; }
        public string Basic_Warranty { get; set; }
        public string Bluetooth { get; set; }
        public string Boot_lid_Opener { get; set; }
        public string Boot_Space { get; set; }
        public string CD_MP3_DVD_Player { get; set; }
        public string Central_Locking { get; set; }
        public string Child_Safety_Locks { get; set; }
        public string Clock { get; set; }
        public string Cup_Holders { get; set; }
        public string Distance_to_Empty { get; set; }
        public string Door_Pockets { get; set; }
        public string Engine_Malfunction_Light { get; set; }
        public string Extended_Warranty { get; set; }
        public string FM_Radio { get; set; }
        public string Fuel_lid_Opener { get; set; }
        public string Fuel_Gauge { get; set; }
        public string Handbrake { get; set; }
        public string Instrument_Console { get; set; }
        public string Low_Fuel_Warning { get; set; }
        public string Minimum_Turning_Radius { get; set; }
        public string Multifunction_Display { get; set; }
        public string Sun_Visor { get; set; }
        public string Third_Row_AC_Vents { get; set; }
        public string Ventilation_System { get; set; }
        public string Auto_Dimming_Rear_View_Mirror { get; set; }
        public string Hill_Assist { get; set; }
        public string Gear_Indicator { get; set; }
        public string C_3_Point_Seat_Belt_in_Middle_Rear_Seat { get; set; }
        public string Ambient_Lightning { get; set; }
        public string Cargo_Boot_Lights { get; set; }
        public string Drive_Modes { get; set; }
        public string Engine_Immobilizer { get; set; }
        public string High_Speed_Alert_System { get; set; }
        public string Lane_Watch_Camera_Side_Mirror_Camera { get; set; }
        public string Passenger_Side_Seat_Belt_Reminder { get; set; }
        public string Seat_Back_Pockets { get; set; }
        public string Voice_Recognition { get; set; }
        public string Walk_Away_Auto_Car_Lock { get; set; }
        public string ABS_Anti_lock_Braking_System { get; set; }
        public string Headlight_Reminder { get; set; }
        public string Adjustable_Headrests { get; set; }
        public string Gross_Vehicle_Weight { get; set; }
        public string Airbags { get; set; }
        public string Door_Ajar_Warning { get; set; }
        public string EBD_Electronic_Brake_force_Distribution { get; set; }
        public string Fasten_Seat_Belt_Warning { get; set; }
        public string Gear_Shift_Reminder { get; set; }
        public string Number_of_Airbags { get; set; }
        public string Compression_Ratio { get; set; }
        public string Adjustable_Steering_Column { get; set; }
        public string Other_Specs { get; set; }
        public string Other_specs1 { get; set; }
        public string Parking_Assistance { get; set; }
        public string Key_Off_Reminder { get; set; }
        public string USB_Compatibility { get; set; }
        public string Android_Auto { get; set; }
        public string Apple_CarPlay { get; set; }
        public string Cigarette_Lighter { get; set; }
        public string Infotainment_Screen { get; set; }
        public string Multifunction_Steering_Wheel { get; set; }
        public string Average_Speed { get; set; }
        public string EBA_Electronic_Brake_Assist { get; set; }
        public string Seat_Height_Adjustment { get; set; }
        public string Navigation_System { get; set; }
        public string Second_Row_AC_Vents { get; set; }
        public string Tyre_Pressure_Monitoring_System { get; set; }
        public string Rear_Center_Armrest { get; set; }
        public string iPod_Compatibility { get; set; }
        public string ESP_Electronic_Stability_Program { get; set; }
        public string Cooled_Glove_Box { get; set; }
        public string Recommended_Tyre_Pressure { get; set; }
        public string Heated_Seats { get; set; }
        public string Turbocharger { get; set; }
        public string ISOFIX_Child_Seat_Mount { get; set; }
        public string Rain_Sensing_Wipers { get; set; }
        public string Paddle_Shifters { get; set; }
        public string Leather_Wrapped_Steering { get; set; }
        public string Automatic_Headlamps { get; set; }
        public string Engine_Type { get; set; }
        public string ASR_Traction_Control { get; set; }
        public string Cruise_Control { get; set; }
        public string USB_Ports { get; set; }
        public string Heads_Up_Display { get; set; }
        public string Welcome_Lights { get; set; }
        public string Battery { get; set; }
        public string Electric_Range { get; set; }
    }
}
